triggers:
  - name: trigger-test-deploy-dv
    type: trigger
    pointer:
      message: 'testing trigger in test 2'

  - name: trigger-test-deploy-box
    type: trigger
    pointer:
      counter: 3
